### ISSUE TITLE
how to add filter to dark mode?

### ISSUE THREAD

**Issue by nekooee** [Larsklopstra/tailwindcss-css-filters#6]
Hi
how to add filters to the dark mode?
I try dark:filter-invert-100 but not work.

**Comment by Larsklopstra** [comment]
Thanks for your issue, this has been fixed now in version `2.1.0`! 😄

**Comment by nekooee** [comment]
@Larsklopstra 
thank you please update your npm package. now you only updated GitHub.

**Comment by Larsklopstra** [comment]
@nekooee it's already on NPM: https://www.npmjs.com/package/tailwindcss-css-filters/v/2.1.0

![image](https://user-images.githubusercontent.com/25669876/109189189-09e80d80-7794-11eb-85d6-dce3b30e7a8b.png)

![image](https://user-images.githubusercontent.com/25669876/109189221-13717580-7794-11eb-8761-adbbda110fd2.png)
